// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWZ46jb0cQzBfklTIjLBhFAEWewJapf38',
    appId: '1:281752654218:android:670055faa192b82fa0f873',
    messagingSenderId: '281752654218',
    projectId: 'eqraclinic',
    storageBucket: 'eqraclinic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZDCv7_sz8rpFoJVs9v8IhrcG2F35QBI',
    appId: '1:281752654218:ios:a9979f7af06b89e8a0f873',
    messagingSenderId: '281752654218',
    projectId: 'eqraclinic',
    storageBucket: 'eqraclinic.appspot.com',
    iosClientId: '281752654218-2v3b5up7fkvbaou5iesk5pbpaslbdo54.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktopMicClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClZDCv7_sz8rpFoJVs9v8IhrcG2F35QBI',
    appId: '1:281752654218:ios:a9979f7af06b89e8a0f873',
    messagingSenderId: '281752654218',
    projectId: 'eqraclinic',
    storageBucket: 'eqraclinic.appspot.com',
    iosClientId: '281752654218-2v3b5up7fkvbaou5iesk5pbpaslbdo54.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktopMicClinic',
  );
}
